- name: Print values from prompt
  vars_prompt:
    - name: MESSAGE
      prompt: Enter the MESSAGE
      private: no
      debug:
        msg: URL = {{URL}} 

        - name: Install Java 
        package:
          name: java 
          state: latest 
        notify: Restart Tomcat 
      