- name: Install Java
  become: yes
  package:
    name: java
    state: latest

- name: Check a tomcat directory exists or not 
  stat:
    path: /home/student/apache-tomcat-{{TOMCAT_VERSION}}
  register: tomcat_dir_check
  
- name: Download Tomcat 
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "/home/centos"
    remote_src: yes
  become: yes
  when: tomcat_dir_check.stat.exists|bool == false

- name: Download TOmcat Init script 
  get_url:
    url: "{{TOMCAT_INIT_SCRIPT_URL}}"
    dest: /etc/init.d/tomcat 
    mode: u=rwx,g=rx,o=rx 
  become: yes
  
- name: Reload Systemctl service 
  systemd:
    daemon_reload: yes
    
- name: Start Tomcat Service 
  service:
    name: tomcat 
    state: started 
  
  



