- name: Install Java
  become: yes
  package:
    name: java
    state: latest

- name: Check a tomcat directory exists or not 
    stat:
      path: /home/student/apache-tomcat-{{TOMCAT_VERSION}}
    register: tomcat_dir_check
  
  - name: Download Tomcat 
    unarchive:
      src: "{{TOMCAT_URL}}"
      dest: "/home/{{APPUSER}}"
      remote_src: yes
    become_user: "{{APPUSER}}"
    when: tomcat_dir_check.stat.exists|bool == false
    notify: Restart Tomcat 
  
  - name: Download StudentApp War file 
    get_url:
      url: "{{WAR_URL}}"
      dest: "/home/{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/webapps"
    become_user: "{{APPUSER}}"
  

