- name: Install Java
  become: yes
  package:
    name: java
    state: latest

- name: Check a tomcat directory exists or not 
  stat:
    path: /home/student/apache-tomcat-{{TOMCAT_VERSION}}
  register: tomcat_dir_check
  
- name: Download Tomcat 
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "/home/centos"
    remote_src: yes
    when: tomcat_dir_check.stat.exists|bool == false



